In [23]:
import numpy as np
from scipy.interpolate import RegularGridInterpolator
def f(x, y, z):
    return 2 * x**3 + 3 * y**2 - z

n = 2
x = np.linspace(1, 2, n)
y = np.linspace(2, 3, n+1)
z = np.linspace(3, 4, n+2)
xg, yg ,zg = np.meshgrid(x, y, z, indexing='ij', sparse=True)
# data = f(xg, yg ,zg)
f_vec = np.vectorize(f)
data = f_vec(xg, yg ,zg)

print(data.shape)
print(data)
interp = RegularGridInterpolator((x, y, z), data)
a = interp([1,2.5,3.5])
# print(a.shape)
# print(a[0])

(2, 3, 4)
[[[11.         10.66666667 10.33333333 10.        ]
  [17.75       17.41666667 17.08333333 16.75      ]
  [26.         25.66666667 25.33333333 25.        ]]

 [[25.         24.66666667 24.33333333 24.        ]
  [31.75       31.41666667 31.08333333 30.75      ]
  [40.         39.66666667 39.33333333 39.        ]]]


In [ ]:
import numpy as np
from scipy.interpolate import RegularGridInterpolator
def f(t,u,v,x, y, z):
    return 2 * x**3 + 3 * y**2 - z + 2 * t**3 + 3 * u**2 - v

n = 11
t = np.linspace(1, 4, n)
u = np.linspace(4, 7, n)
v = np.linspace(7, 9, n)
x = np.linspace(1, 4, n)
y = np.linspace(4, 7, n)
z = np.linspace(7, 9, n)
tg, ug ,vg, xg, yg ,zg = np.meshgrid(t, u, v, x, y, z, indexing='ij', sparse=True)
data = f(tg, ug ,vg, xg, yg ,zg)

print(data)
interp = RegularGridInterpolator((t, u, v, x, y, z), data)
a = interp([2,5,8,2,5,8])
a[0]

[[[[[[ 86.     85.8    85.6   ...  84.4    84.2    84.   ]
     [ 93.47   93.27   93.07  ...  91.87   91.67   91.47 ]
     [101.48  101.28  101.08  ...  99.88   99.68   99.48 ]
     ...
     [160.88  160.68  160.48  ... 159.28  159.08  158.88 ]
     [172.67  172.47  172.27  ... 171.07  170.87  170.67 ]
     [185.    184.8   184.6   ... 183.4   183.2   183.   ]]

    [[ 88.394  88.194  87.994 ...  86.794  86.594  86.394]
     [ 95.864  95.664  95.464 ...  94.264  94.064  93.864]
     [103.874 103.674 103.474 ... 102.274 102.074 101.874]
     ...
     [163.274 163.074 162.874 ... 161.674 161.474 161.274]
     [175.064 174.864 174.664 ... 173.464 173.264 173.064]
     [187.394 187.194 186.994 ... 185.794 185.594 185.394]]

    [[ 92.192  91.992  91.792 ...  90.592  90.392  90.192]
     [ 99.662  99.462  99.262 ...  98.062  97.862  97.662]
     [107.672 107.472 107.272 ... 106.072 105.872 105.672]
     ...
     [167.072 166.872 166.672 ... 165.472 165.272 165.072]
     [178.862 178.662 178

166.60800000000006